### ISSUE TITLE
add out box

### ISSUE THREAD

**Issue by asukaminato0721** [JerryI/Mathematica-ThreeJS-graphics-engine#16]
I am testing plot3d.

![image](https://user-images.githubusercontent.com/30024051/213873100-d70660d2-9297-47f6-96ef-1acbd2ab5db8.png)

but the AspectRatio is strange.

![image](https://user-images.githubusercontent.com/30024051/213873184-4c8f1cf9-364c-4c71-b13a-d94b288197b4.png)

but I think it's acceptable. :). Since the graph is correct.

but missing the box outside makes it hard to "feel the space".

Then I found this may help. https://threejs.org/docs/#api/en/helpers/BoxHelper

But where to add it is a problem, since there may have many objects in a scene.

**Comment by paulmasson** [comment]
@wuyudi I would suggest adding the `BoxHelper` outside of all objects in the scene. Here's an example from one of my libraries:

https://github.com/paulmasson/mathcell/blob/master/src/render/threejs-template.js#L63

For this to work you of course need to run through all the input objects and find minimum and maximum extents in all three directions.
