### ISSUE TITLE
add test / examples

### ISSUE THREAD

**Issue by wuyudi** [JerryI/Mathematica-ThreeJS-graphics-engine#17]
currently, this project is missing the test.

there may be 2 ways to test:

1. test the single function.
2. test generates pictures as a whole, I guess one way is to take a screenshot and compare the result vs the expected.

---

Because copying and pasting the JSON and seeing the rendered result is such a pain. :(

**Comment by JerryI** [comment]
Yeah
I was thinking before to automate it using Wolfram Engine.

**Comment by JerryI** [comment]
![Screenshot 2023-01-22 at 13 46 16](https://user-images.githubusercontent.com/4111822/213916552-1199ebec-4698-475d-a5cc-be49deacb594.png)
 Done!
