### ISSUE TITLE
Use Three.js OrbitControls for navigation

### ISSUE THREAD

**Issue by paulmasson** [JerryI/Mathematica-ThreeJS-graphics-engine#2]
Instead of maintaining your own navigation code, why not use the existing OrbitControls or one of the others? The Detector.js file you are currently using is  a Three.js component, now named WebGL.js in the examples directory. It would not be difficult to use the existing controls as well and save yourself some effort in the future.

**Comment by wuyudi** [comment]
I found this example: the code is much short.

OrbitControls: https://threejs.org/examples/#misc_controls_orbit

by the way, the current code uses some attributes of `THREE.Geometry`, which makes the migration to BufferGeometry harder.

**Comment by paulmasson** [comment]
This issue can be closed once https://github.com/JerryI/Mathematica-ThreeJS-graphics-engine/issues/10#issuecomment-1401106266 is addressed
