### ISSUE TITLE
remove THREE.Geometry

### ISSUE THREAD

**Issue by wuyudi** [JerryI/Mathematica-ThreeJS-graphics-engine#20]
as the title said, Geometry is removed from three.js, so it's better to remove it here.

But since they are different, so remove it is harder than I think. : (

**Comment by JerryI** [comment]
Almost Done. As a bonus in dev brach there is now RTX support ;))
![Screenshot 2023-07-16 at 16 10 16](https://github.com/JerryI/Mathematica-ThreeJS-graphics-engine/assets/4111822/48d56362-99c4-46fe-9ec9-df64f79c6d2f)
![Screenshot 2023-07-16 at 15 58 09](https://github.com/JerryI/Mathematica-ThreeJS-graphics-engine/assets/4111822/b5e376f8-cae1-42e9-81e3-c08d8c4066ef)

**Comment by JerryI** [comment]
![Screenshot from 2023-07-19 18-34-23](https://github.com/JerryI/Mathematica-ThreeJS-graphics-engine/assets/4111822/d6f01bc0-5283-46a3-91ad-a817c1860d7a)
![Screenshot from 2023-07-19 19-26-24](https://github.com/JerryI/Mathematica-ThreeJS-graphics-engine/assets/4111822/412f8527-0dd7-446e-926a-070f31dfb442)
![screenshot(4)](https://github.com/JerryI/Mathematica-ThreeJS-graphics-engine/assets/4111822/742b0ec1-39d0-4901-9242-a5581c773c3f)
