### ISSUE TITLE
[Feature Request] Export individual plot as HTML which can be added to another article.

### ISSUE THREAD

**Issue by colcav** [JerryI/Mathematica-ThreeJS-graphics-engine#31]
Based on Rousan's question in the Telegram Support chat. I am also interested in this feature! 

Currently, an entire notebook can be exported as HTML. However, extracting a given graphic from this HTML file is complex and difficult. A feature which enables a single graphic to be saved or exported, such that this graphic can be embedded in a new article, would be great!

**Comment by JerryI** [comment]
++ We are working on MDX export, since it might be easier to embed. But in principle, in the end this will be a JSON file and a few JS libs included to the header of your blog/page.

**Comment by colcav** [comment]
Gotcha! That sounds great. Thanks for the quick reply.

Col

**Comment by colcav** [comment]
Do you all have a sense of when you expect to have the MDX export up and
running? No rush, of course -- just wondering if you have an estimate!

Many thanks,
Col

**Comment by JerryI** [comment]
> Do you all have a sense of when you expect to have the MDX export up and running? No rush, of course -- just wondering if you have an estimate! Many thanks, Col On Wed, Jul 17, 2024 at 8:58 AM Col Cavanaugh ***@***.***> wrote:

Since this is feature attracts a lot of attention. This probably will be the next step.
The current plan is

- _18-20 Jul_ - New major update of WLJS (bug fixes, polished editor...)
- _end of Jul - beginning of August_ - MDX export or HTML, whatever fits better

Best,
Kirill

**Comment by colcav** [comment]
Good to know! Thanks a bunch.

Col

**Comment by JerryI** [comment]
We rolled out it in a new release. Here is how it looks


https://github.com/user-attachments/assets/82935e55-54d5-4b0c-8c9b-aaddfa95d921
