### ISSUE TITLE
What is the preferred way to show a list of Graphics3D expressions?

### ISSUE THREAD

**Issue by axkr** [JerryI/Mathematica-ThreeJS-graphics-engine#4]
What is the preferred way to show a list of `Graphics3D[ ]`expressions?

**Comment by JerryI** [comment]
You can type in the web-browser console `core` and the list will pop up

![Screenshot 2023-01-17 at 15 42 20](https://user-images.githubusercontent.com/4111822/212928470-f7681766-c4ea-460d-9415-8fbd58ef649c.png)
